---
- hosts: ios
  gather_facts: no
  tasks:
    - name: configure ip access list
      ios_config:
        lines:
          - 10 permit ip host 192.0.2.1 any log
          - 20 permit ip host 192.0.2.2 any log
          - 30 permit ip host 192.0.2.3 any log
          - 40 permit ip host 192.0.2.4 any log
          - 50 permit ip host 192.0.2.5 any log
        parents: ip access-list extended ansible-demo
        before: no ip access-list extended ansible-demo
    - name: configurable backup path
      ios_config:
        src: ios_template.j2
        backup: yes
        backup_options:
          filename: backup.cfg
          dir_path: ./
