# resource_group_name     = "pwaller_web_RG"
resource_group_location = "UKWest"
storage_account_name   = "pwa5269storage"
account_tier            = "Standard"
account_replication_type = "LRS"
storage_container = "pwstorageconainer5269"
storage_blob = "terraform.state"